language: python
python:
  - "3.6.3"
# command to install dependencies
install:
  - pip install -r dependencies.txt
# command to run tests
script:
  - app.py # or py.test for Python versions 3.5 and below